INSERT INTO
  ratings(user_id, rating, service_id, comment)
VALUES
  (1, 3, 1, 'I was very happy with the service provided.'),
  (2, 4, 2, 'Myfront yard was perfect.'),
  (2, 4, 3, 'It was fast affordable.'),
  (2, 4, 4, 'Amazing service.'),
  (1, 4, 5, 'Not good.'),
  (3, 4, 6, 'Very expensive.'),
  (3, 4, 7, 'Very frendly.'),
  (3, 4, 8, 'Super!!'),
  (4, 4, 9, 'My garden looks amazing.'),
  (4, 4, 10, 'My car seems a mirror now.'),
  (5, 4, 11, 'One of my frame got broken'),
  (5, 2, 12, 'nice guy'),
  (1, 2, 14, 'will call again'),
  (1, 5, 18, 'took 5 day to get done'),
  (3, 4, 19, 'Stay away!'),
  (2, 5, 22, 'Not as expected.'),
  (4, 5, 24, 'Professional and fast.'),
  (5, 1, 26, 'Good'),
  (1, 1, 29, 'No more stain, great job!'),
  (2, 3, 25, 'Now my home is dust free.'),
  (3, 2, 21, 'Always good!'),
  (4, 4, 7, 'The best.');