DROP TABLE IF EXISTS sellers CASCADE;

CREATE TABLE sellers (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  address VARCHAR(255) NOT NULL,
  lat REAL  NOT NULL,
  lng REAL  NOT NULL,
  picture_url TEXT NOT NULL,
  phone VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);