DROP TABLE IF EXISTS orders_services CASCADE;

CREATE TABLE orders_services (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  service_id INTEGER REFERENCES services(id) ON DELETE CASCADE
);